export type RequirementCategory = "identity"|"academic"|"language"|"admission"|"funding"|"research"|"references"|"experience"|"documents"|"application"|"programme"|"other";
export interface ExtractedRequirement { name:string; required:boolean; category:RequirementCategory; details:string; conditional?:string; sourceInstruction:string; evidence:string; }

type Rule={name:string;category:RequirementCategory;patterns:RegExp[];details:string};

// These rules intentionally describe requirements rather than generating application answers.
// Evidence is always retained so the UI can show the source wording/context behind each item.
const rules:Rule[]=[
 {name:"Academic transcript",category:"academic",patterns:[/transcript/i,/academic record/i,/statement of results/i,/marks sheet/i],details:"Official academic transcript or equivalent institutional academic record. Capture whether it must show all semesters/years, grades, credit units, grading scale, cumulative result, institution seal/signature, certification, translation and whether an interim transcript is accepted."},
 {name:"Degree certificate",category:"academic",patterns:[/degree certificate/i,/certificate of graduation/i,/graduation certificate/i,/diploma certificate/i],details:"Proof that the qualifying degree has been completed. Capture whether a final certificate is mandatory, whether applicants awaiting graduation may submit a provisional/completion letter, and whether certified copies or translations are required."},
 {name:"Curriculum vitae / resume",category:"documents",patterns:[/curriculum vitae/i,/\bcv\b/i,/resume/i],details:"Current CV/resume. Capture required maximum length, format, language, whether education, employment, research, fieldwork, publications, projects, volunteering and technical skills should be included, and whether a specific template is mandatory."},
 {name:"Personal statement / statement of purpose",category:"application",patterns:[/personal statement/i,/statement of purpose/i,/\bsop\b/i,/motivation letter/i,/motivation statement/i],details:"Written statement explaining academic motivation, programme fit, objectives and expected outcomes. Capture every stated prompt/question, word or character limit, page limit, language, file format and whether the statement is scholarship-specific or admission-specific."},
 {name:"Research proposal / study plan",category:"research",patterns:[/research proposal/i,/research plan/i,/study proposal/i,/study plan/i,/research statement/i],details:"Research or study plan. Capture mandatory sections such as problem/background, objectives, research questions, methodology, literature/context, expected outputs, timeline, references, relevance to the programme/funder, supervisor fit, word/page limit, template and formatting rules."},
 {name:"Recommendation / reference letters",category:"references",patterns:[/recommendation letter/i,/reference letter/i,/letters of recommendation/i,/academic referee/i,/professional referee/i,/referee/i,/recommendation/i],details:"Recommendation evidence. Capture exact number of referees, academic/professional status, minimum relationship or seniority, institutional affiliation, contact details, confidentiality, submission mechanism, referee deadline and whether letters must be on letterhead or signed."},
 {name:"English-language proficiency",category:"language",patterns:[/ielts/i,/toefl/i,/pte academic/i,/cambridge english/i,/english language proficiency/i,/proof of english/i,/english test/i,/language requirement/i],details:"Proof of English-language ability where explicitly required. Capture accepted tests, minimum overall score, minimum component/sub-score requirements, validity period, test-date restrictions, exemptions, accepted alternatives and whether the condition applies to scholarship selection, university admission or both."},
 {name:"Other language proficiency",category:"language",patterns:[/language proficiency/i,/language certificate/i,/proof of language/i,/german language/i,/french language/i,/japanese language/i],details:"Language evidence other than English. Capture the exact language, accepted certificates/tests, minimum level, component requirements, exemptions and whether proof is required at application, admission or enrolment."},
 {name:"Passport / identity document",category:"identity",patterns:[/passport/i,/proof of identity/i,/national id/i,/identification document/i],details:"Valid identity document used to establish identity and/or nationality. Capture acceptable document types, expiry/validity rules, whether the biographical page is sufficient, certification/translation requirements and whether the document is required at application or only after selection."},
 {name:"Proof of nationality / citizenship",category:"identity",patterns:[/proof of nationality/i,/citizenship certificate/i,/nationality/i,/citizenship/i],details:"Evidence establishing nationality/citizenship when nationality is an eligibility condition. Capture acceptable evidence, dual-nationality conditions, citizenship-by-birth/naturalisation conditions and whether residence is also relevant."},
 {name:"Proof of residence",category:"identity",patterns:[/proof of residence/i,/residence permit/i,/residency/i,/proof of domicile/i,/resident status/i],details:"Evidence of residence or legal residency where eligibility depends on where the applicant lives. Capture eligible residence period, acceptable documents and whether nationality and residence must be in the same country."},
 {name:"Admission / university application",category:"admission",patterns:[/admission application/i,/apply for admission/i,/university application/i,/offer of admission/i,/admission offer/i,/letter of admission/i],details:"Separate university/programme admission requirement. Capture whether admission is required before scholarship application, before award, before travel or before enrolment; whether the applicant must apply separately; and every admission deadline and portal involved."},
 {name:"Programme eligibility / qualifying degree",category:"programme",patterns:[/relevant degree/i,/related degree/i,/qualifying degree/i,/eligible programme/i,/field of study/i,/academic background/i,/subject area/i],details:"Prior qualification and subject-area requirement. Record the exact disciplines, degree titles, departments or programme areas named by the official source. Do not assume that an adjacent degree is equivalent unless the source says so."},
 {name:"Minimum GPA / CGPA / grade",category:"academic",patterns:[/minimum gpa/i,/minimum cgpa/i,/minimum grade/i,/grade point average/i,/academic excellence/i,/upper second/i,/second class upper/i,/distinction/i],details:"Academic performance threshold. Capture exact minimum score, grading scale, degree classification, percentage equivalent, conversion method, whether the threshold applies to cumulative performance or a particular period, and any country-specific equivalency rules."},
 {name:"Academic ranking / class standing",category:"academic",patterns:[/class rank/i,/ranked in the top/i,/top \d+%/i,/class standing/i,/academic ranking/i],details:"Academic standing requirement beyond GPA. Capture exact ranking threshold, cohort definition, evidence required and whether the institution must certify the ranking."},
 {name:"Relevant coursework / prerequisite subjects",category:"academic",patterns:[/prerequisite/i,/prerequisite course/i,/required coursework/i,/relevant coursework/i,/required subjects/i,/prerequisite subjects/i],details:"Specific prior coursework or subject prerequisites. Capture exact subjects, minimum grades/credits, recency rules and whether equivalent coursework is accepted."},
 {name:"Work / professional experience",category:"experience",patterns:[/work experience/i,/professional experience/i,/years of experience/i,/relevant experience/i,/professional background/i],details:"Professional experience requirement or preference. Capture minimum duration, eligible sectors/roles, full-time/part-time rules, date window, geographic conditions and whether volunteer, internship, research or community experience is explicitly counted."},
 {name:"Research experience",category:"research",patterns:[/research experience/i,/research background/i,/research skills/i,/research project/i,/research training/i],details:"Prior research experience or demonstrated research capability. Capture mandatory versus preferred status and acceptable evidence such as thesis, dissertation, research project, assistantship, laboratory work, field study or research employment."},
 {name:"Publications / scholarly output",category:"research",patterns:[/publication/i,/peer-reviewed/i,/journal article/i,/scholarly output/i,/conference paper/i,/book chapter/i],details:"Publications or scholarly outputs. Capture whether publications are mandatory or preferred, accepted publication types, authorship requirements, publication status, DOI/links, copies and evidence of contribution."},
 {name:"Research methods / technical skills",category:"research",patterns:[/research methods/i,/methodological skills/i,/quantitative methods/i,/qualitative methods/i,/statistical software/i,/data analysis skills/i],details:"Research-method or technical-skill condition. Capture named methods/software, minimum proficiency evidence, whether training is expected and whether the condition is mandatory or merely advantageous."},
 {name:"Supervisor / host confirmation",category:"research",patterns:[/supervisor/i,/supervisory agreement/i,/host institution/i,/host confirmation/i,/faculty member/i,/potential supervisor/i],details:"Supervisor, host or departmental support requirement. Capture whether prior contact is mandatory, whether a named supervisor must agree before application, whether a supervisor letter is required, and what proof of contact/acceptance must be supplied."},
 {name:"Research fit / thematic alignment",category:"research",patterns:[/research interests/i,/research fit/i,/research topic/i,/research area/i,/thematic area/i,/alignment with/i],details:"Alignment with the programme, supervisor, laboratory, department, research group or funding theme. Capture the exact thematic priorities and any requirement to demonstrate fit. A keyword match alone is not treated as proof of eligibility."},
 {name:"Financial need / financial evidence",category:"funding",patterns:[/financial need/i,/proof of funds/i,/financial statement/i,/household income/i,/income certificate/i,/means test/i],details:"Financial-need or financial-capacity evidence. Capture the financial period, household definition, income/assets considered, acceptable evidence, currency/conversion rules and whether financial need is an eligibility criterion or a selection factor."},
 {name:"Funding-specific conditions",category:"funding",patterns:[/funding condition/i,/funding agreement/i,/funding requirements/i,/scholarship terms/i,/award conditions/i],details:"Conditions attached to the financial award. Capture tuition coverage, stipend/living allowance, travel, accommodation, insurance, visa costs, dependants, research allowance, books/equipment, duration, renewal conditions, academic progress requirements and exclusions."},
 {name:"Application form / online portal",category:"application",patterns:[/application form/i,/online application/i,/application portal/i,/submit an application/i,/apply online/i],details:"Official application mechanism. Capture account creation, portal name, required sections, separate scholarship and admission portals, document-upload rules, file formats/size limits, save/submit behaviour, confirmation messages and whether submission can be edited after finalisation."},
 {name:"Application fee",category:"application",patterns:[/application fee/i,/application charge/i,/fee waiver/i],details:"Application fee or waiver. Distinguish scholarship fees from university admission fees. Capture amount/currency, payment deadline, accepted payment methods, waiver criteria and whether payment is refundable."},
 {name:"Application deadlines",category:"application",patterns:[/deadline/i,/closing date/i,/applications? close/i,/apply by/i,/last day to apply/i],details:"Submission timing. Capture exact date, time and timezone where stated; scholarship versus admission deadlines; document/reference deadlines; rolling admissions; staged deadlines; country-specific deadlines; and whether late applications are accepted."},
 {name:"Application stages / selection process",category:"application",patterns:[/selection process/i,/selection criteria/i,/selection procedure/i,/shortlisted/i,/shortlist/i,/assessment process/i],details:"Selection stages and criteria. Capture screening, shortlist, interview, nomination, institutional review, final selection, notification timing and any separate stages that can eliminate an otherwise eligible applicant."},
 {name:"Interview / selection interview",category:"application",patterns:[/interview/i,/selection interview/i,/oral interview/i,/panel interview/i],details:"Interview or selection stage. Capture mandatory versus shortlisted status, format (online/in-person), likely language, panel/stage, scheduling requirements and whether missing the interview eliminates the application."},
 {name:"Writing sample",category:"documents",patterns:[/writing sample/i,/sample of writing/i,/academic writing sample/i],details:"Academic, professional or research writing sample. Capture maximum length, topic, authorship, language, recency, acceptable document types and whether it must be an existing piece or written specifically for the opportunity."},
 {name:"Portfolio",category:"documents",patterns:[/portfolio/i,/work portfolio/i],details:"Portfolio or evidence of previous work. Capture required format, number/size of items, links versus files, file-size limits and any field-specific content requirements."},
 {name:"Proof of employment / experience",category:"documents",patterns:[/employment certificate/i,/employment letter/i,/proof of employment/i,/experience certificate/i,/employer letter/i],details:"Evidence supporting employment or professional experience. Capture acceptable issuer, dates, job title, duties, hours/status and whether signed/stamped documentation is required."},
 {name:"Proof of research / project work",category:"documents",patterns:[/research certificate/i,/thesis/i,/dissertation/i,/research project report/i,/project report/i],details:"Evidence supporting research or project experience. Capture whether a thesis/project title, abstract, supervisor confirmation, report, publication, dataset, repository link or other evidence is required."},
 {name:"Proof of awards / achievements",category:"documents",patterns:[/award certificate/i,/academic award/i,/achievement/i,/honour/i,/honors/i],details:"Evidence of awards or achievements when explicitly requested. Capture which achievements qualify and whether certificates, institutional verification or other evidence is required."},
 {name:"Medical / health documentation",category:"identity",patterns:[/medical examination/i,/medical certificate/i,/health certificate/i,/health examination/i,/medical report/i],details:"Medical or health documentation. Capture who may issue it, required tests/examinations, validity period, approved forms, timing and whether it is needed for scholarship selection, visa or enrolment."},
 {name:"Police / background certificate",category:"identity",patterns:[/police clearance/i,/criminal record/i,/background check/i,/police certificate/i],details:"Police, criminal-record or background documentation where explicitly required. Capture issuing authority, country, recency/validity, translation/certification and submission stage."},
 {name:"Visa / immigration evidence",category:"identity",patterns:[/visa/i,/immigration status/i,/residence permit/i,/student visa/i],details:"Visa or immigration condition. Distinguish application-stage evidence from post-award/arrival obligations and capture the exact immigration status permitted or required."},
 {name:"Age requirement",category:"identity",patterns:[/age limit/i,/under \d+ years/i,/over \d+ years/i,/born after/i,/born before/i,/age requirement/i],details:"Age-related eligibility condition. Capture exact age/date-of-birth cutoff, reference date, exemptions and whether the rule differs by scholarship track or nationality."},
 {name:"Nationality / country eligibility",category:"identity",patterns:[/eligible countries/i,/eligible nationalities/i,/nationalities eligible/i,/citizens of/i,/nationals of/i,/country eligibility/i,/countries eligible/i],details:"Nationality/country eligibility. Capture included countries, excluded countries, citizenship versus residence distinction, dual-nationality conditions and any country-specific tracks."},
 {name:"Return-home / residence obligation",category:"funding",patterns:[/return to your country/i,/return home/i,/return requirement/i,/home country/i,/reside in your home country/i],details:"Post-award return or residence obligation. Capture required return destination, duration, exceptions, enforcement/contract conditions and whether the obligation applies to all awardees."},
 {name:"Post-award service / employment obligation",category:"funding",patterns:[/service obligation/i,/bonded/i,/bond period/i,/work in your country/i,/serve your country/i],details:"Post-award service or employment obligation. Capture required service duration, eligible employer/location, start point and consequences or repayment conditions where stated."},
 {name:"Full-time study requirement",category:"programme",patterns:[/full-time study/i,/full time study/i,/full-time enrolment/i,/full time enrolment/i],details:"Study-load requirement. Capture whether the programme must be full-time, minimum credit/load requirements, permitted part-time status and any exceptions."},
 {name:"Programme duration requirement",category:"programme",patterns:[/duration of the programme/i,/programme duration/i,/course duration/i,/minimum duration/i,/maximum duration/i],details:"Programme-duration condition affecting eligibility or funding. Capture minimum/maximum duration, funded period, extension rules and whether funding ends before programme completion."},
 {name:"Eligible institution / university",category:"programme",patterns:[/eligible universities/i,/eligible institution/i,/participating universities/i,/partner university/i,/host university/i,/approved institution/i],details:"Institution eligibility. Capture the exact participating/approved universities, departments or partner institutions and any restriction on where the applicant may enrol."},
 {name:"Eligible programme / course",category:"programme",patterns:[/eligible programmes/i,/eligible courses/i,/eligible master/i,/eligible degree programmes/i,/approved programmes/i],details:"Programme-specific eligibility. Capture exact programme names, departments, study modes, campus/location restrictions and exclusions."},
 {name:"Scholarship nomination requirement",category:"application",patterns:[/nomination/i,/nominated by/i,/institutional nomination/i,/national nomination/i],details:"Nomination requirement. Capture who must nominate the applicant, nomination limits, internal deadlines, whether self-application is possible and whether nomination precedes the scholarship application."},
 {name:"Institutional endorsement",category:"admission",patterns:[/institutional endorsement/i,/university endorsement/i,/institution endorsement/i,/endorsement letter/i],details:"Formal endorsement from an institution or authority. Capture who can endorse, required wording/form, internal deadline and whether the endorsement is distinct from a reference or admission offer."},
 {name:"Document certification / legalisation",category:"documents",patterns:[/certified copy/i,/certified document/i,/legalised/i,/legalization/i,/apostille/i,/notarized/i,/notarised/i],details:"Document authenticity requirement. Capture which documents need certification/legalisation, who may certify them, acceptable authorities, translation rules and whether certification is required at application or after selection."},
 {name:"Official translation",category:"documents",patterns:[/official translation/i,/certified translation/i,/translated into english/i,/translation into english/i],details:"Translation requirement for documents not issued in the accepted language. Capture accepted translator/certification, which documents need translation and whether originals must accompany translations."},
 {name:"Document format / file limits",category:"application",patterns:[/pdf only/i,/file size/i,/maximum file size/i,/file format/i,/upload format/i,/document format/i],details:"Technical document-submission constraints. Capture accepted formats, maximum file size, page limits, naming conventions, scan quality and whether colour/scanned/original documents are required."},
 {name:"Declaration / consent",category:"application",patterns:[/declaration/i,/consent/i,/privacy consent/i,/declaration of accuracy/i,/terms and conditions/i],details:"Applicant declaration or consent. Capture statements that must be accepted, accuracy/false-information declarations, data-processing consent and any consequences stated for inaccurate information."},
 {name:"Application account / registration",category:"application",patterns:[/create an account/i,/register on the portal/i,/registration/i,/account creation/i],details:"Portal registration requirement. Capture account creation steps, email verification, identity/account restrictions, duplicate-account rules and whether registration must occur before a deadline."},
 {name:"Funding duration / renewal",category:"funding",patterns:[/renewable/i,/renewal/i,/funding period/i,/award duration/i,/renewed/i],details:"Funding duration and continuation conditions. Capture funded months/years, renewal criteria, academic progress requirements, annual reviews and whether extensions are funded."},
 {name:"Tuition / fee coverage",category:"funding",patterns:[/tuition fees/i,/tuition waiver/i,/tuition covered/i,/fees covered/i,/fee waiver/i],details:"Tuition/fee coverage. Capture whether tuition is fully or partially covered, which mandatory fees are included/excluded, payment mechanism and any fee cap."},
 {name:"Stipend / living allowance",category:"funding",patterns:[/stipend/i,/living allowance/i,/maintenance allowance/i,/monthly allowance/i,/living costs/i],details:"Living-cost support. Capture amount, currency, payment frequency, duration, eligibility conditions and whether the amount is fixed, estimated or subject to change."},
 {name:"Travel / relocation support",category:"funding",patterns:[/travel allowance/i,/travel grant/i,/airfare/i,/flight/i,/relocation/i,/travel costs/i],details:"Travel or relocation support. Capture what travel is covered, number of trips, route restrictions, reimbursement versus direct booking and eligible dependants where explicitly stated."},
 {name:"Accommodation / housing support",category:"funding",patterns:[/accommodation/i,/housing allowance/i,/housing costs/i,/residential costs/i],details:"Accommodation support. Capture whether housing is provided, subsidised or paid as an allowance, duration, eligibility and any accommodation conditions."},
 {name:"Health insurance coverage",category:"funding",patterns:[/health insurance/i,/medical insurance/i,/insurance coverage/i],details:"Insurance benefit. Capture coverage scope, duration, exclusions and whether the applicant must purchase insurance independently before reimbursement."},
 {name:"Research / study allowance",category:"funding",patterns:[/research allowance/i,/research grant/i,/study allowance/i,/book allowance/i,/equipment allowance/i],details:"Additional study/research support. Capture amount or cap, eligible expenses, reimbursement rules and whether approval is needed before spending."},
 {name:"Application instructions acknowledgement",category:"application",patterns:[/read the application guidelines/i,/application guidelines/i,/applicant guidelines/i,/instructions for applicants/i],details:"Compliance with official application instructions. Capture any mandatory acknowledgement, checklist, declarations or instruction-specific conditions that could invalidate a submission."}
];

const sectionPattern=/(?:required documents|application documents|supporting documents|documents required|how to apply|application requirements|eligibility criteria|who can apply|selection criteria|application process|what you need|requirements)[\s:]*([\s\S]{0,20000})/i;
const optionalPattern=/\b(optional|if applicable|where applicable|may submit|not required|preferred|desirable|encouraged|recommended)\b/i;
const requiredPattern=/\b(required|must|mandatory|need to|shall|compulsory|essential)\b/i;

export function extractApplicationRequirements(input:string):ExtractedRequirement[]{
 const text=normalizeText(input); const section=text.match(sectionPattern)?.[1]??text; const out:ExtractedRequirement[]=[]; const seen=new Set<string>();
 for(const rule of rules){let hit:RegExpMatchArray|undefined;for(const p of rule.patterns){const m=section.match(p);if(m){hit=m;break;}}if(!hit)continue;
   const context=contextAround(section,hit.index??0); const key=rule.name.toLowerCase(); if(seen.has(key))continue; seen.add(key);
   const optional=optionalPattern.test(context); const explicitlyRequired=requiredPattern.test(context);
   out.push({name:rule.name,required:explicitlyRequired?!optional:!optional,category:rule.category,details:rule.details,conditional:conditionalClause(context),sourceInstruction:context.slice(0,1600),evidence:context.slice(0,3000)});
 }
 return out;
}

function normalizeText(value:string){return value.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<noscript[\s\S]*?<\/noscript>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g," ").trim();}
function contextAround(text:string,index:number){return text.slice(Math.max(0,index-650),Math.min(text.length,index+1900)).trim();}
function conditionalClause(context:string):string|undefined{const match=context.match(/\b(?:if|where|when|for|provided that|unless|only if|subject to)\b[^.]{0,280}[.]/i);return match?.[0]?.trim();}
